# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
GMAIL_USERNAME: Your_Username
GMAIL_PASSWORD: Your_Password
ADMIN_NAME: First User
ADMIN_EMAIL: user@example.com
ADMIN_PASSWORD: changeme
ROLES: [admin]
AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
AWS_REGION: eu-west-1
AWS_ZONE: eu-west-1a
AWS_SSH_USER: ubuntu
CODECLIMATE_REPO_TOKEN: a2eb7fbe2c195fad5f2cf575e5e84b73f45eb5b7700cf169a8e2e8e054ab755e
DISABLE_COVERALLS:
RAILS_SECRET_KEY_BASE: 28420dc03c0d95982b888635b627b3b0594c82c6c8fd14fbd0e151c097ffbb44fa2767c875fe7ff563d679efd34770f4fea4602cecbe56b5406e5247b6d49234
SERVER_ID: testmaster-asl-eth.renuo.ch # or localhost for development
MLMQ_DB_AWS_ID: i-ec666ea3
MLMQ_DB_URL: jdbc:postgresql://#{host}:5432 # ?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
MLMQ_DB_NAME: TODO_SET_DB_NAME
MLMQ_DB_USER: TODO_SET_DB_USER
MLMQ_DB_PASSWORD: TODO_SET_DB_PASSWORD
