development:
  adapter: postgresql
  username: postgres
  password:
  database: testmaster_<%= Rails.env %>
  min_messages: ERROR
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  username: postgres
  password:
  database: testmaster_<%= Rails.env %>
  min_messages: ERROR
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  username: postgres
  password:
  database: testmaster_<%= Rails.env %>
  min_messages: ERROR
  pool: 5
  timeout: 5000
  host: localhost

